files:
    profile: 
        load file2chan
        load std
        ndb/cs
        test -d /mnt/registry || mkdir -p /mnt/registry

        GCLOUD_DIR = /tmp/gcloud/cmd
        mount -A tcp!registry.dev.metacoma.io!30099 /mnt/registry
        test -d $GCLOUD_DIR || mkdir -p $GCLOUD_DIR
        chmod a+rwx $GCLOUD_DIR
        echo --- you are here
        dir = /
        port = 1917
        port2 = 2000
        echo --- after ports


        file2chan $GCLOUD_DIR^/gcloud {
            if {~ ${rget offset} 0} {
                cat $output_file | putrdata
            } {
                rread ''
            }
            } {
            load mpexpr
            var=${expr 10 rand}
            echo new id is $var
            echo hostname is `{os hostname}
            (key project zone) = `{echo ${rget data}} 
            echo $project
            echo $zone
            mkdir -p /host/$var
            `{os /bin/bash -c 'mkdir -p /accounts/'^$var^''}
            `{os /bin/bash -c 'echo '^$key^' | base64 -d > /accounts/'^$var^'/key'}
            `{os /bin/bash -c 'gcloud auth activate-service-account --key-file /accounts/'^$var^'/key --quiet'}
            `{os /bin/bash -c 'cat /accounts/'^$var^'/key | jq .client_email > /accounts/'^$var^'/email'}
            `{os /bin/bash -c 'echo '^$project^' > /accounts/'^$var^'/project'}
            `{os /bin/bash -c 'echo '^$zone^' > /accounts/'^$var^'/zone'}
            sh -n -c 'os execfuse-static /execfuse-fs /usr/inferno-os/host/$var'
            grid/reglisten -A -r description 'user id is $var' tcp!*!2000 { export /host/^$var & } &
            }
        chmod a+rwx $GCLOUD_DIR^/gcloud
        echo --- after file2chan
        listen -A -t 'tcp!*!'$port { export /tmp/gcloud & } &